推送镜像到coding

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,7 +5,7 @@ on:
   # Allow manual triggering of the workflow from the Actions tab
   workflow_dispatch:
 
-  # Allow inputs to be passed when manually triggering the workflow from the Actions tab
+    # Allow inputs to be passed when manually triggering the workflow from the Actions tab
     inputs:
       DOCKERFILE_PATH:
         type: string
@@ -34,58 +34,58 @@ on:
 jobs:
 
   guard_clause:
-      runs-on: ubuntu-latest
-  
-      env:
-        GH_TOKEN: ${{ github.token }} # As required by the GitHub-CLI  
+    runs-on: ubuntu-latest
 
-      permissions:
-        actions: 'write' # Required in order to terminate the workflow run.
-  
-      steps:
-        - uses: actions/checkout@v4
-        # Guard clause that cancels the workflow in case of an invalid DOCKERFILE_PATH and/or incorrectly configured Github Pages. 
-        # The main reason for choosing this workaround for aborting the workflow is the fact that it does not display the workflow as successful, which can set false expectations.
-        - name: DOCKERFILE_PATH.
-          shell: bash
-          run: |
-            # We check whether the Dockerfile_path is valid. 
-            if [ ! -f ${{ github.event.inputs.DOCKERFILE_PATH }} ]; then
-                echo "::error title=Invalid Dockerfile path::No file found at ${{ github.event.inputs.DOCKERFILE_PATH }}"
-                echo "terminate=true" >> $GITHUB_ENV
-            fi
+    env:
+      GH_TOKEN: ${{ github.token }} # As required by the GitHub-CLI
 
-        - name: Github Pages config guard clause
-          if: ${{ github.event.inputs.DEPLOY_TO_GITHUB_PAGES == 'true' }}
-          run: |
-            # We use the Github Rest api to get information regarding pages for the Github Repository and store it into a temporary file named "pages_response".
-            set +e
-            gh api \
-              -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository_owner }}/$(basename ${{ github.repository }})/pages > pages_response
+    permissions:
+      actions: 'write' # Required in order to terminate the workflow run.
 
-            # We make sure Github Pages has been enabled for this repository.
-            if [ "$?" -ne 0 ]; then
-              echo "::error title=Potential pages configuration error.::Please make sure you have enabled Github pages for the ${{ github.repository }} repository. If already enabled then Github pages might be down"
+    steps:
+      - uses: actions/checkout@v4
+      # Guard clause that cancels the workflow in case of an invalid DOCKERFILE_PATH and/or incorrectly configured Github Pages.
+      # The main reason for choosing this workaround for aborting the workflow is the fact that it does not display the workflow as successful, which can set false expectations.
+      - name: DOCKERFILE_PATH.
+        shell: bash
+        run: |
+          # We check whether the Dockerfile_path is valid. 
+          if [ ! -f ${{ github.event.inputs.DOCKERFILE_PATH }} ]; then
+              echo "::error title=Invalid Dockerfile path::No file found at ${{ github.event.inputs.DOCKERFILE_PATH }}"
               echo "terminate=true" >> $GITHUB_ENV
-            fi
-            set -e
+          fi
 
-            # We make sure the Github pages build & deployment source is set to "workflow" (Github Actions). Instead of a "legacy" (branch).
-            if [[ "$(jq --compact-output --raw-output .build_type pages_response)" != "workflow" ]]; then
-                echo "Undefined behaviour, Make sure the Github Pages source is correctly configured in the Github Pages settings."
-                echo "::error title=Pages configuration error.::Please make sure you have correctly picked \"Github Actions\" as the build and deployment source for the Github Pages."
-                echo "terminate=true" >> $GITHUB_ENV
-            fi
-            rm pages_response
+      - name: Github Pages config guard clause
+        if: ${{ github.event.inputs.DEPLOY_TO_GITHUB_PAGES == 'true' }}
+        run: |
+          # We use the Github Rest api to get information regarding pages for the Github Repository and store it into a temporary file named "pages_response".
+          set +e
+          gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/${{ github.repository_owner }}/$(basename ${{ github.repository }})/pages > pages_response
+          
+          # We make sure Github Pages has been enabled for this repository.
+          if [ "$?" -ne 0 ]; then
+            echo "::error title=Potential pages configuration error.::Please make sure you have enabled Github pages for the ${{ github.repository }} repository. If already enabled then Github pages might be down"
+            echo "terminate=true" >> $GITHUB_ENV
+          fi
+          set -e
+          
+          # We make sure the Github pages build & deployment source is set to "workflow" (Github Actions). Instead of a "legacy" (branch).
+          if [[ "$(jq --compact-output --raw-output .build_type pages_response)" != "workflow" ]]; then
+              echo "Undefined behaviour, Make sure the Github Pages source is correctly configured in the Github Pages settings."
+              echo "::error title=Pages configuration error.::Please make sure you have correctly picked \"Github Actions\" as the build and deployment source for the Github Pages."
+              echo "terminate=true" >> $GITHUB_ENV
+          fi
+          rm pages_response
 
-        - name: Terminate run if error occurred.
-          run: |
-            if [[ $terminate == "true" ]]; then
-              gh run cancel ${{ github.run_id }}
-              gh run watch ${{ github.run_id }}
-            fi
+      - name: Terminate run if error occurred.
+        run: |
+          if [[ $terminate == "true" ]]; then
+            gh run cancel ${{ github.run_id }}
+            gh run watch ${{ github.run_id }}
+          fi
 
   build:
     needs: guard_clause # Dependency
@@ -108,13 +108,30 @@ jobs:
         id: image_name_gen
         run: |
           echo "IMAGE_NAME=$(basename ${{ github.event.inputs.DOCKERFILE_PATH }})_$(date +%Y%m%d)_${{ github.run_id }}.ext2" >> $GITHUB_ENV
+          echo "PACKAGE=$(basename ${{ github.event.inputs.DOCKERFILE_PATH }})" >> $GITHUB_ENV
+          echo "VERSION=$(date +%Y%m%d)_${{ github.run_id }}" >> $GITHUB_ENV
 
       # Create directory to host the image from.
       - run: sudo mkdir -p $DEPLOY_DIR
 
       # Build the i386 Dockerfile image.
       - run: docker build . --tag $TAG --file ${{ github.event.inputs.DOCKERFILE_PATH }} --platform=i386
-      
+
+      # 新增步骤：登录 Coding Docker 仓库
+      - name: Login to Coding Docker Registry
+        run: |
+          docker login -u ${{ secrets.CODING_USER }} -p ${{ secrets.CODING_TOKEN }} e64-docker.pkg.coding.net
+
+      # 新增步骤：重新打标签
+      - name: Tag Docker image
+        run: |
+          docker tag $TAG e64-docker.pkg.coding.net/webvm/webvm/${{ env.PACKAGE }}:${{ env.VERSION }}
+
+      # 新增步骤：推送镜像
+      - name: Push Docker image
+        run: |
+          docker push e64-docker.pkg.coding.net/webvm/webvm/${{ env.PACKAGE }}:${{ env.VERSION }}
+
       # Run the docker image so that we can export the container.
       # Run the Docker container with the Google Public DNS nameservers: 8.8.8.8, 8.8.4.4
       - run: |
@@ -148,18 +165,18 @@ jobs:
       # We create and mount the base ext2 image to extract the Docker container's filesystem its contents into.
       - name: Create ext2 image.
         run: |
-         # Preallocate space for the ext2 image
-         sudo fallocate -l $IMAGE_SIZE ${IMAGE_NAME}
-         # Format to ext2 linux kernel revision 0
-         sudo mkfs.ext2 -r 0 ${IMAGE_NAME}
-         # Mount the ext2 image to modify it
-         sudo mount -o loop -t ext2 ${IMAGE_NAME} /mnt/
+          # Preallocate space for the ext2 image
+          sudo fallocate -l $IMAGE_SIZE ${IMAGE_NAME}
+          # Format to ext2 linux kernel revision 0
+          sudo mkfs.ext2 -r 0 ${IMAGE_NAME}
+          # Mount the ext2 image to modify it
+          sudo mount -o loop -t ext2 ${IMAGE_NAME} /mnt/
 
       # We opt for 'docker cp --archive' over 'docker save' since our focus is solely on the end product rather than individual layers and metadata.
       # However, it's important to note that despite being specified in the documentation, the '--archive' flag does not currently preserve uid/gid information when copying files from the container to the host machine.
       # Another compelling reason to use 'docker cp' is that it preserves resolv.conf.
       - name: Export and unpack container filesystem contents into mounted ext2 image.
-        run: | 
+        run: |
           sudo docker cp -a ${CONTAINER_ID}:/ /mnt/
           sudo umount /mnt/
       # Result is an ext2 image for webvm.
